import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from 'next/font/google';
import Navbar from "./components/navbar/Navbar";
import Footer from "./components/Footer/Footer";

const poppins = Poppins({
  weight: ['400', '700'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: "Rent Lease",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
